# Site settings
title: 青森大学ご飯マップ
email: kokubo@aomori-u.ac.jp
description: > # this means to ignore newlines until "baseurl:"
  青森大学周辺のご飯を食べられる/買えるところをマップにしました。
  銀行や郵便局も載ってます。
baseurl: "/aomori-univ-gohan-map" # the subpath of your site, e.g. /blog/
url: "http://akokubo.github.io" # the base hostname & protocol for your site
twitter_username: akokubo
github_username:  akokubo

# Build settings
markdown: kramdown
